In [2]:
import sys
sys.version


'2.7.12 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:43:17) \n[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]'

In [3]:
import skimage.io as io
from skimage.viewer import ImageViewer as IV

/Users/liutongyang/anaconda/lib/python2.7/site-packages/skimage/viewer/utils/core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "


In [4]:
import numpy as np

In [5]:
c = io.imread('chronometer.tif')

In [6]:
c.shape[0]/2

1846

In [7]:
c.ndim

2

In [8]:
c.dtype

dtype('uint8')

In [9]:
c.size

10381904

In [10]:
a = np.array([1,2,3,4,5,6,7,8])

In [11]:
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a[0:9:2]

array([1, 3, 5, 7])

In [13]:
c2 = np.ndarray(shape = (c.shape[0]/2,c.shape[1]/2), dtype = "uint8")

In [14]:
for i in range(0,c.shape[0],2):
    c2[i/2,:] = c[i,:][1:c.shape[1]:2]

In [15]:
c2.shape

(1846, 1406)

In [16]:
vc2 = IV(c2)

In [17]:
vc2.show()

[]

In [24]:
c16 = np.ndarray(shape = (len(range(0,c.shape[0],16)),len(c[1,:][1:c.shape[1]:16])), dtype = "uint8")

In [25]:
for i in range(0,c.shape[0],16):
    c16[i/16,:] = c[i,:][1:c.shape[1]:16]

In [38]:
tt[1,1] 

2.0

In [42]:
c16resize = np.ndarray(shape = (c16.shape[0]*16,c16.shape[1]*16), dtype = "uint8")

In [43]:
for i in range(0,c16.shape[0]):
    for j in range(0,c16.shape[1]):
        for h in range(i*16,(i+1)*16):
            for k in range(j*16,(j+1)*16):
                c16resize[h,k] = c16[i,j]

In [50]:
v = IV(c16resize)

In [51]:
v.show()

[]

In [46]:
vc16 = IV(c16)

In [52]:
vc16.show()

RuntimeError: wrapped C/C++ object of type ImageViewer has been deleted

In [55]:
c16resize[1500][0:160]

array([246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246, 246,
       246, 246, 246, 246, 246, 246, 246, 246, 245, 245, 245, 245, 245,
       245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245,
       245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245,
       245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245, 245,
       245, 245, 245, 245], dtype=uint8)

In [1]:
from skimage.viewer import ImageViewer as IV
import skimage.io as io
import numpy as np

resample_size = 32
c = io.imread('chronometer.tif')

c_smaller = np.ndarray(shape = (len(range(0,c.shape[0],resample_size)),len(c[1,:][1:c.shape[1]:resample_size])), dtype = "uint8")

for i in range(0,c.shape[0],resample_size):
    c_smaller[i/resample_size,:] = c[i,:][1:c.shape[1]:resample_size]

c_resize = np.ndarray(shape = (c_smaller.shape[0]*resample_size,c_smaller.shape[1]*resample_size), dtype = "uint8")
for i in range(0,c_smaller.shape[0]):
    for j in range(0,c_smaller.shape[1]):
        for h in range(i*resample_size,(i+1)*resample_size):
            for k in range(j*resample_size,(j+1)*resample_size):
                c_resize[h,k] = c_smaller[i,j]

v = IV(c_resize)
v.show()

/Users/liutongyang/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/liutongyang/anaconda/lib/python2.7/site-packages/skimage/viewer/utils/core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "


[]

In [2]:
c_resize.shape

(3712, 2816)

In [49]:
d = io.imread("dollar.tif")

In [4]:
d.shape

(500, 1192)

In [5]:
d.size

596000

In [19]:
d_bin = np.ndarray(shape = d.shape)

In [41]:
bit_plane1 = {}

In [42]:
bit_plane1["dfsad"] = 2

NameError: name 'bit_plane1' is not defined

In [43]:
d = ["d1",'d2']

In [44]:
d[1]

'd2'

In [45]:
a = np.array([1,2])

In [50]:
d.shape

(500, 1192)

In [51]:
d_bin = np.ndarray(shape = (500,1192,8))

In [52]:
for i in range(0,d.shape[0]):
    for j in range(0,d.shape[1]):
        for p in range(0,8):
            d_bin[i,j,p] = int('{0:08b}'.format(d[i,j])[::-1][p])*(2**6)

In [56]:
tt = IV(d_bin[:,:,0])

In [22]:
d1 = np.ndarray(shape = d.shape)
d2 = np.ndarray(shape = d.shape)
d3 = np.ndarray(shape = d.shape)
d4 = np.ndarray(shape = d.shape)
d5 = np.ndarray(shape = d.shape)
d6 = np.ndarray(shape = d.shape)
d7 = np.ndarray(shape = d.shape)
d8 = np.ndarray(shape = d.shape)

In [59]:
matplotlib.imshow(tt)

NameError: name 'matplotlib' is not defined

In [92]:
a = np.empty(500)

In [98]:
a[400:500] = 250

In [99]:
b = np.ones(500)

In [100]:
mat = np.outer(a,b)

In [101]:
tt = IV(mat)

In [ ]:
tt.show()

In [17]:
a[100]

0.19607843137254902

In [11]:
a.astype("uint8")

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,
        13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  1

In [18]:
a = np.empty(500)
a[0:100] = 0
a[100:200] = 50
a[200:300] = 100
a[300:400] = 200
a[400:500] = 255
a = a/255.0
b = np.ones(500)
mat = np.outer(a,b)
tt = IV(mat)
tt.show()

[]

In [12]:
tt = IV(mat)
tt.show()

[]

In [10]:
mat.astype(int)

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ..., 
       [250, 250, 250, ..., 250, 250, 250],
       [250, 250, 250, ..., 250, 250, 250],
       [250, 250, 250, ..., 250, 250, 250]])

In [5]:
gray = io.imread("Gray.jpg")

In [15]:
gray.shape

(600, 800, 3)

In [20]:
gray[400,511]

array([85, 85, 85], dtype=uint8)

In [1]:
import matplotlib.pyplot as plt 

/Users/liutongyang/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [6]:
plt.imshow(gray)

In [ ]:
plt.show()

In [ ]:
4

In [ ]:
import numpy